In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from google.colab import files

In [2]:
print("Upload fashion_products.csv")

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

df = pd.read_csv(file_name)

df.head()

Upload fashion_products.csv

Saving fashion_products(1).csv to fashion_products(1).csv

,Product_ID,Product_Name,Category,Color,Style,Brand,Price_INR,Rating,Image_File
0,P001,EliteFit T-Shirt,T-Shirt,Red,Streetwear,EliteFit,2725,4.9,images/product_001.png
1,P002,Nova Shirt,Shirt,Beige,Sporty,Nova,2459,4.2,images/product_002.png
2,P003,TrendX Jeans,Jeans,Brown,Formal,TrendX,2503,4.8,images/product_003.png
3,P004,UrbanWear Dress,Dress,Blue,Ethnic,UrbanWear,3612,4.1,images/product_004.png
4,P005,StyleHub Hoodie,Hoodie,Pink,Casual,StyleHub,3423,4.1,images/product_005.png

In [3]:
print("Dataset Shape:", df.shape)

df.head(10)

Dataset Shape: (50, 9)

,Product_ID,Product_Name,Category,Color,Style,Brand,Price_INR,Rating,Image_File
0,P001,EliteFit T-Shirt,T-Shirt,Red,Streetwear,EliteFit,2725,4.9,images/product_001.png
1,P002,Nova Shirt,Shirt,Beige,Sporty,Nova,2459,4.2,images/product_002.png
2,P003,TrendX Jeans,Jeans,Brown,Formal,TrendX,2503,4.8,images/product_003.png
3,P004,UrbanWear Dress,Dress,Blue,Ethnic,UrbanWear,3612,4.1,images/product_004.png
4,P005,StyleHub Hoodie,Hoodie,Pink,Casual,StyleHub,3423,4.1,images/product_005.png
5,P006,EliteFit Jacket,Jacket,Yellow,Streetwear,EliteFit,1565,4.0,images/product_006.png
6,P007,Nova Kurti,Kurti,White,Sporty,Nova,1729,3.7,images/product_007.png
7,P008,TrendX Skirt,Skirt,Green,Formal,TrendX,517,3.9,images/product_008.png
8,P009,UrbanWear Top,Top,Grey,Ethnic,UrbanWear,3360,4.9,images/product_009.png
9,P010,StyleHub Sneakers,Sneakers,Black,Casual,StyleHub,631,4.0,images/product_010.png

In [4]:
df = df.fillna("")

df["combined_features"] = (
    df["Category"].astype(str)
    + " "
    + df["Color"].astype(str)
    + " "
    + df["Style"].astype(str)
    + " "
    + df["Brand"].astype(str)
)

df[["Product_Name","combined_features"]].head()

       Product_Name                combined_features
0  EliteFit T-Shirt  T-Shirt Red Streetwear EliteFit
1        Nova Shirt          Shirt Beige Sporty Nova
2      TrendX Jeans        Jeans Brown Formal TrendX
3   UrbanWear Dress      Dress Blue Ethnic UrbanWear
4   StyleHub Hoodie      Hoodie Pink Casual StyleHub

In [5]:
vectorizer = TfidfVectorizer()

feature_vectors = vectorizer.fit_transform(
    df["combined_features"]
)

print("Feature Extraction Completed")

Feature Extraction Completed

In [6]:
similarity = cosine_similarity(
    feature_vectors
)

print("Similarity Matrix Created")

Similarity Matrix Created

In [7]:
def recommend(product_name):

    matched = df[
        df["Product_Name"]
        .str.contains(
            product_name,
            case=False,
            na=False
        )
    ]

    if len(matched) == 0:
        print("Product Not Found")
        return

    index = matched.index[0]

    similarity_scores = list(
        enumerate(similarity[index])
    )

    sorted_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    print("\nTop Recommended Products:\n")

    count = 0

    for i, score in sorted_scores[1:]:

        print(
            "Product:",
            df.iloc[i]["Product_Name"]
        )

        print(
            "Category:",
            df.iloc[i]["Category"]
        )

        print(
            "Brand:",
            df.iloc[i]["Brand"]
        )

        print(
            "Price:",
            "₹",
            df.iloc[i]["Price_INR"]
        )

        print(
            "Rating:",
            df.iloc[i]["Rating"]
        )

        print("---------------------")

        count += 1

        if count == 5:
            break

In [8]:
product = input(
    "Enter Product Name: "
)

recommend(product)

Enter Product Name: nova shirt

Top Recommended Products:

Product: Nova Shirt
Category: Shirt
Brand: Nova
Price: ₹ 1561
Rating: 3.6
---------------------
Product: Nova Shirt
Category: Shirt
Brand: Nova
Price: ₹ 2221
Rating: 4.5
---------------------
Product: Nova Shirt
Category: Shirt
Brand: Nova
Price: ₹ 3949
Rating: 3.9
---------------------
Product: Nova Shirt
Category: Shirt
Brand: Nova
Price: ₹ 3044
Rating: 4.1
---------------------
Product: Nova Kurti
Category: Kurti
Brand: Nova
Price: ₹ 1729
Rating: 3.7
---------------------

In [9]:
df.sample(10)

,Product_ID,Product_Name,Category,Color,Style,Brand,Price_INR,Rating,Image_File,combined_features
24,P025,StyleHub Hoodie,Hoodie,Pink,Casual,StyleHub,2488,4.5,images/product_025.png,Hoodie Pink Casual StyleHub
25,P026,EliteFit Jacket,Jacket,Yellow,Streetwear,EliteFit,2701,4.1,images/product_026.png,Jacket Yellow Streetwear EliteFit
39,P040,StyleHub Sneakers,Sneakers,Black,Casual,StyleHub,3866,3.5,images/product_040.png,Sneakers Black Casual StyleHub
15,P016,EliteFit Jacket,Jacket,Yellow,Streetwear,EliteFit,1105,4.6,images/product_016.png,Jacket Yellow Streetwear EliteFit
44,P045,StyleHub Hoodie,Hoodie,Pink,Casual,StyleHub,1185,3.7,images/product_045.png,Hoodie Pink Casual StyleHub
7,P008,TrendX Skirt,Skirt,Green,Formal,TrendX,517,3.9,images/product_008.png,Skirt Green Formal TrendX
22,P023,TrendX Jeans,Jeans,Brown,Formal,TrendX,1024,4.8,images/product_023.png,Jeans Brown Formal TrendX
27,P028,TrendX Skirt,Skirt,Green,Formal,TrendX,2798,3.6,images/product_028.png,Skirt Green Formal TrendX
10,P011,EliteFit T-Shirt,T-Shirt,Red,Streetwear,EliteFit,1401,4.9,images/product_011.png,T-Shirt Red Streetwear EliteFit
8,P009,UrbanWear Top,Top,Grey,Ethnic,UrbanWear,3360,4.9,images/product_009.png,Top Grey Ethnic UrbanWear

In [10]:
print("""
Fashion Recommendation System
implemented successfully.

Technique Used:
Content-Based Filtering

Algorithm:
TF-IDF + Cosine Similarity

Output:
Personalized Fashion Recommendations
generated successfully.
""")

Fashion Recommendation System
implemented successfully.

Technique Used:
Content-Based Filtering

Algorithm:
TF-IDF + Cosine Similarity

Output:
Personalized Fashion Recommendations
generated successfully.